#
# Copyright 2021 by Swiss Post, Information Technology Services
#
#

version: "2.4"

services:
  database:
    image: ${DOCKER_REGISTRY}/ev/h2:0.11.0
    container_name: h2
    hostname: h2
    security_opt:
      - no-new-privileges
    networks:
      - area-database
    ports:
      - "8082:8082"
      - "9093:9093"

  authentication:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=AUTHENTICATION
      DATABASE_DRIVER: org.h2.Driver

  certificate-registry:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CERTIFICATE_REGISTRY
      DATABASE_DRIVER: org.h2.Driver

  election-information:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=ELECTION_INFORMATION
      DATABASE_DRIVER: org.h2.Driver

  extended-authentication:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=EXTENDED_AUTHENTICATION
      DATABASE_DRIVER: org.h2.Driver

  vote-verification:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTE_VERIFICATION
      DATABASE_DRIVER: org.h2.Driver

  voter-material:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTER_MATERIAL
      DATABASE_DRIVER: org.h2.Driver

  voting-workflow:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTING_WORKFLOW
      DATABASE_DRIVER: org.h2.Driver

  orchestrator:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=ORCHESTRATOR
      DATABASE_DRIVER: org.h2.Driver

  return-codes-1:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=RETURN_CODES_1
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  return-codes-2:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=RETURN_CODES_2
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  return-codes-3:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=RETURN_CODES_3
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  return-codes-4:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=RETURN_CODES_4
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  distributed-mixing-1:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=DISTRIBUTED_MIXING_1
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  distributed-mixing-2:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=DISTRIBUTED_MIXING_2
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  distributed-mixing-3:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=DISTRIBUTED_MIXING_3
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver
