#
# Copyright 2021 by Swiss Post, Information Technology Services
#
#

version: "2.4"

services:
  database:
    image: ${DOCKER_REGISTRY}/ev/h2:${EVOTING_VERSION}
    container_name: h2
    hostname: h2
    security_opt:
      - no-new-privileges
    networks:
      - area-database
    ports:
      - "8082:8082"
      - "9093:9093"

  authentication:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=AUTHENTICATION
      DATABASE_DRIVER: org.h2.Driver

  certificate-registry:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CERTIFICATE_REGISTRY
      DATABASE_DRIVER: org.h2.Driver

  election-information:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=ELECTION_INFORMATION
      DATABASE_DRIVER: org.h2.Driver

  extended-authentication:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=EXTENDED_AUTHENTICATION
      DATABASE_DRIVER: org.h2.Driver

  vote-verification:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTE_VERIFICATION
      DATABASE_DRIVER: org.h2.Driver

  voter-material:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTER_MATERIAL
      DATABASE_DRIVER: org.h2.Driver

  voting-workflow:
    environment:
      DATABASE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=VOTING_WORKFLOW
      DATABASE_DRIVER: org.h2.Driver

  message-broker-orchestrator:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=MESSAGE_BROKER_ORCHESTRATOR
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  control-component-1:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CONTROL_COMPONENT_1
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  control-component-2:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CONTROL_COMPONENT_2
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  control-component-3:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CONTROL_COMPONENT_3
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver

  control-component-4:
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:9093/~/h2db1;MODE=Oracle;DATABASE_TO_UPPER=true;SCHEMA=CONTROL_COMPONENT_4
      SPRING_DATASOURCE_DRIVER_CLASS: org.h2.Driver
